// generator.go — CLI 命令生成器核心逻辑
// 从 swagger Endpoint 列表生成 Cobra 命令代码（Layer 2）
package registry

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"gitee.com/unitedrhino/cli/internal/swagger"
)

func title(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// GenerateOptions 控制生成行为
type GenerateOptions struct {
	OutputDir   string // 输出目录（如 ./cmd/generated/）
	PackageName string // 生成代码的包名
}

// Generate 从 swagger 端点生成 Go 代码文件
func Generate(endpoints []swagger.Endpoint, opts GenerateOptions) error {
	if opts.PackageName == "" {
		opts.PackageName = "generated"
	}
	if opts.OutputDir == "" {
		opts.OutputDir = "cmd/generated"
	}

	// 按 group 分组
	groups := groupByGroup(endpoints)

	// 为每个 group 生成一个文件
	for group, eps := range groups {
		filename := filepath.Join(opts.OutputDir, sanitizeName(group)+".go")
		if err := generateFile(filename, opts.PackageName, group, eps); err != nil {
			return fmt.Errorf("generate %s: %w", filename, err)
		}
	}

	return nil
}

func groupByGroup(endpoints []swagger.Endpoint) map[string][]swagger.Endpoint {
	groups := make(map[string][]swagger.Endpoint)
	for _, ep := range endpoints {
		g := extractGroupFromPath(ep.Path)
		if g == "" {
			g = "core"
		}
		groups[g] = append(groups[g], ep)
	}
	return groups
}

func extractGroupFromPath(path string) string {
	// 从 /api/v1/things/... 提取 things
	// 从 /api/v1/system/... 提取 system
	parts := strings.Split(path, "/")
	if len(parts) >= 4 && parts[1] == "api" && parts[2] == "v1" {
		return parts[3]
	}
	return ""
}

func sanitizeName(s string) string {
	// 将非法字符替换为下划线，生成合法的 Go 标识符
	s = strings.ReplaceAll(s, "/", "_")
	s = strings.ReplaceAll(s, "-", "_")
	return s
}

func generateFile(filename, pkg, group string, endpoints []swagger.Endpoint) error {
	// 按资源分组
	byResource := make(map[string][]swagger.Endpoint)
	for _, ep := range endpoints {
		byResource[ep.Resource] = append(byResource[ep.Resource], ep)
	}

	// 排序资源名
	var resources []string
	for r := range byResource {
		resources = append(resources, r)
	}
	sort.Strings(resources)

	data := struct {
		Package    string
		Group      string
		Resources  []resourceData
	}{
		Package: pkg,
		Group:   group,
	}

	for _, r := range resources {
		rd := resourceData{Name: sanitizeName(r), OriginalName: r}
		for _, ep := range byResource[r] {
			action := ep.Action
			if action == "" {
				action = extractActionFromPath(ep.Path)
			}
			useName := strings.ReplaceAll(action, "_", "-")
			varName := strings.ReplaceAll(action, "-", "_")
			// 确保同一 resource 下变量名唯一
			varName = makeUnique(rd.Commands, varName)
			rd.Commands = append(rd.Commands, commandData{
				Name:        varName,
				UseName:     useName,
				Path:        ep.Path,
				Method:      ep.Method,
				Summary:     ep.Summary,
				Description: ep.Description,
			})
		}
		data.Resources = append(data.Resources, rd)
	}

	tmpl, err := template.New("generated").Funcs(template.FuncMap{
		"title": title,
	}).Parse(fileTemplate)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(filename), 0755); err != nil {
		return err
	}
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	return tmpl.Execute(f, data)
}

type resourceData struct {
	Name         string // 合法的 Go 标识符
	OriginalName string // 原始资源名（用于命令 Use）
	Commands     []commandData
}

type commandData struct {
	Name        string // 合法的 Go 标识符（下划线）
	UseName     string // 用户看到的命令名（连字符）
	Path        string
	Method      string
	Summary     string
	Description string
}

func actionToCommandName(action string) string {
	if action == "" {
		return "call"
	}
	// 将连字符替换为下划线，生成合法的 Go 标识符
	return strings.ReplaceAll(action, "-", "_")
}

func makeUnique(commands []commandData, name string) string {
	seen := make(map[string]bool)
	for _, c := range commands {
		seen[c.Name] = true
	}
	if !seen[name] {
		return name
	}
	for i := 2; ; i++ {
		candidate := fmt.Sprintf("%s_%d", name, i)
		if !seen[candidate] {
			return candidate
		}
	}
}

func extractActionFromPath(path string) string {
	parts := strings.Split(strings.TrimRight(path, "/"), "/")
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return "call"
}

const fileTemplate = `// Code generated by cmd/generate. DO NOT EDIT.

package {{ .Package }}

import (
	"fmt"

	"github.com/spf13/cobra"
	"gitee.com/unitedrhino/cli/internal/client"
)

// Register{{ title .Group }}Commands 注册 {{ .Group }} 组的 Layer 2 API 命令
func Register{{ title .Group }}Commands(parent *cobra.Command) {
{{- range .Resources }}
	{{- $resourceName := .Name }}
	{{ .Name }}Cmd := &cobra.Command{
		Use:   "{{ .OriginalName }}",
		Short: "{{ .OriginalName }} API 操作",
	}
{{- range .Commands }}
	{{ $resourceName }}_{{ .Name }}Cmd := &cobra.Command{
		Use:   "{{ .UseName }}",
		Short: "{{ .Summary }}",
		Long:  "{{ .Description }}",
		RunE: func(cmd *cobra.Command, args []string) error {
			resp, err := client.DoAPI(cmd.Context(), client.APIRequest{
				Path: "{{ .Path }}",
				Body: map[string]any{},
			})
			if err != nil {
				return err
			}
			fmt.Println(resp)
			return nil
		},
	}
	{{ $resourceName }}Cmd.AddCommand({{ $resourceName }}_{{ .Name }}Cmd)
{{- end }}
	parent.AddCommand({{ .Name }}Cmd)
{{- end }}
}
`
